
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  DarkEnAccreditations: typeof import("../../components/dark-en/Accreditations.vue")['default']
  DarkEnBlog: typeof import("../../components/dark-en/Blog.vue")['default']
  DarkEnCTA: typeof import("../../components/dark-en/CTA.vue")['default']
  DarkEnFooter: typeof import("../../components/dark-en/Footer.vue")['default']
  DarkEnHeader: typeof import("../../components/dark-en/Header.vue")['default']
  DarkEnHero: typeof import("../../components/dark-en/Hero.vue")['default']
  DarkEnServices: typeof import("../../components/dark-en/Services.vue")['default']
  DarkEnTeam: typeof import("../../components/dark-en/Team.vue")['default']
  DarkEnTestimonials: typeof import("../../components/dark-en/Testimonials.vue")['default']
  DarkEnWhyUs: typeof import("../../components/dark-en/WhyUs.vue")['default']
  DarkAccreditations: typeof import("../../components/dark/Accreditations.vue")['default']
  DarkBlog: typeof import("../../components/dark/Blog.vue")['default']
  DarkCTA: typeof import("../../components/dark/CTA.vue")['default']
  DarkFooter: typeof import("../../components/dark/Footer.vue")['default']
  DarkHeader: typeof import("../../components/dark/Header.vue")['default']
  DarkHero: typeof import("../../components/dark/Hero.vue")['default']
  DarkServices: typeof import("../../components/dark/Services.vue")['default']
  DarkTeam: typeof import("../../components/dark/Team.vue")['default']
  DarkTestimonials: typeof import("../../components/dark/Testimonials.vue")['default']
  DarkWhyUs: typeof import("../../components/dark/WhyUs.vue")['default']
  Landing2Accreditations: typeof import("../../components/landing-2/Accreditations.vue")['default']
  Landing2AccreditationsEn: typeof import("../../components/landing-2/AccreditationsEn.vue")['default']
  Landing2Blog: typeof import("../../components/landing-2/Blog.vue")['default']
  Landing2BlogEn: typeof import("../../components/landing-2/BlogEn.vue")['default']
  Landing2CTA: typeof import("../../components/landing-2/CTA.vue")['default']
  Landing2CTAEn: typeof import("../../components/landing-2/CTAEn.vue")['default']
  Landing2Footer: typeof import("../../components/landing-2/Footer.vue")['default']
  Landing2FooterEn: typeof import("../../components/landing-2/FooterEn.vue")['default']
  Landing2Header: typeof import("../../components/landing-2/Header.vue")['default']
  Landing2HeaderEn: typeof import("../../components/landing-2/HeaderEn.vue")['default']
  Landing2Hero: typeof import("../../components/landing-2/Hero.vue")['default']
  Landing2HeroEn: typeof import("../../components/landing-2/HeroEn.vue")['default']
  Landing2Services: typeof import("../../components/landing-2/Services.vue")['default']
  Landing2ServicesEn: typeof import("../../components/landing-2/ServicesEn.vue")['default']
  Landing2Team: typeof import("../../components/landing-2/Team.vue")['default']
  Landing2TeamEn: typeof import("../../components/landing-2/TeamEn.vue")['default']
  Landing2Testimonials: typeof import("../../components/landing-2/Testimonials.vue")['default']
  Landing2TestimonialsEn: typeof import("../../components/landing-2/TestimonialsEn.vue")['default']
  Landing2WhyUs: typeof import("../../components/landing-2/WhyUs.vue")['default']
  Landing2WhyUsEn: typeof import("../../components/landing-2/WhyUsEn.vue")['default']
  Landing3Accreditations: typeof import("../../components/landing-3/Accreditations.vue")['default']
  Landing3AccreditationsEn: typeof import("../../components/landing-3/AccreditationsEn.vue")['default']
  Landing3Blog: typeof import("../../components/landing-3/Blog.vue")['default']
  Landing3BlogEn: typeof import("../../components/landing-3/BlogEn.vue")['default']
  Landing3CTA: typeof import("../../components/landing-3/CTA.vue")['default']
  Landing3CTAEn: typeof import("../../components/landing-3/CTAEn.vue")['default']
  Landing3Footer: typeof import("../../components/landing-3/Footer.vue")['default']
  Landing3FooterEn: typeof import("../../components/landing-3/FooterEn.vue")['default']
  Landing3Header: typeof import("../../components/landing-3/Header.vue")['default']
  Landing3HeaderEn: typeof import("../../components/landing-3/HeaderEn.vue")['default']
  Landing3Hero: typeof import("../../components/landing-3/Hero.vue")['default']
  Landing3HeroEn: typeof import("../../components/landing-3/HeroEn.vue")['default']
  Landing3Services: typeof import("../../components/landing-3/Services.vue")['default']
  Landing3ServicesEn: typeof import("../../components/landing-3/ServicesEn.vue")['default']
  Landing3ServicesSlider: typeof import("../../components/landing-3/ServicesSlider.vue")['default']
  Landing3ServicesSliderEn: typeof import("../../components/landing-3/ServicesSliderEn.vue")['default']
  Landing3Team: typeof import("../../components/landing-3/Team.vue")['default']
  Landing3TeamEn: typeof import("../../components/landing-3/TeamEn.vue")['default']
  Landing3Testimonials: typeof import("../../components/landing-3/Testimonials.vue")['default']
  Landing3TestimonialsEn: typeof import("../../components/landing-3/TestimonialsEn.vue")['default']
  Landing3WhyUs: typeof import("../../components/landing-3/WhyUs.vue")['default']
  Landing3WhyUsEn: typeof import("../../components/landing-3/WhyUsEn.vue")['default']
  Landing4Accreditations: typeof import("../../components/landing-4/Accreditations.vue")['default']
  Landing4AccreditationsEn: typeof import("../../components/landing-4/AccreditationsEn.vue")['default']
  Landing4Blog: typeof import("../../components/landing-4/Blog.vue")['default']
  Landing4BlogEn: typeof import("../../components/landing-4/BlogEn.vue")['default']
  Landing4CTA: typeof import("../../components/landing-4/CTA.vue")['default']
  Landing4CTAEn: typeof import("../../components/landing-4/CTAEn.vue")['default']
  Landing4Footer: typeof import("../../components/landing-4/Footer.vue")['default']
  Landing4FooterEn: typeof import("../../components/landing-4/FooterEn.vue")['default']
  Landing4Header: typeof import("../../components/landing-4/Header.vue")['default']
  Landing4HeaderEn: typeof import("../../components/landing-4/HeaderEn.vue")['default']
  Landing4Hero: typeof import("../../components/landing-4/Hero.vue")['default']
  Landing4HeroEn: typeof import("../../components/landing-4/HeroEn.vue")['default']
  Landing4Services: typeof import("../../components/landing-4/Services.vue")['default']
  Landing4ServicesEn: typeof import("../../components/landing-4/ServicesEn.vue")['default']
  Landing4ServicesSlider: typeof import("../../components/landing-4/ServicesSlider.vue")['default']
  Landing4ServicesSliderEn: typeof import("../../components/landing-4/ServicesSliderEn.vue")['default']
  Landing4Team: typeof import("../../components/landing-4/Team.vue")['default']
  Landing4TeamEn: typeof import("../../components/landing-4/TeamEn.vue")['default']
  Landing4Testimonials: typeof import("../../components/landing-4/Testimonials.vue")['default']
  Landing4TestimonialsEn: typeof import("../../components/landing-4/TestimonialsEn.vue")['default']
  Landing4WhyUs: typeof import("../../components/landing-4/WhyUs.vue")['default']
  Landing4WhyUsEn: typeof import("../../components/landing-4/WhyUsEn.vue")['default']
  LightEnAccreditations: typeof import("../../components/light-en/Accreditations.vue")['default']
  LightEnBlog: typeof import("../../components/light-en/Blog.vue")['default']
  LightEnCTA: typeof import("../../components/light-en/CTA.vue")['default']
  LightEnFooter: typeof import("../../components/light-en/Footer.vue")['default']
  LightEnHeader: typeof import("../../components/light-en/Header.vue")['default']
  LightEnHero: typeof import("../../components/light-en/Hero.vue")['default']
  LightEnServices: typeof import("../../components/light-en/Services.vue")['default']
  LightEnTeam: typeof import("../../components/light-en/Team.vue")['default']
  LightEnTestimonials: typeof import("../../components/light-en/Testimonials.vue")['default']
  LightEnWhyUs: typeof import("../../components/light-en/WhyUs.vue")['default']
  LightAccreditations: typeof import("../../components/light/Accreditations.vue")['default']
  LightBlog: typeof import("../../components/light/Blog.vue")['default']
  LightCTA: typeof import("../../components/light/CTA.vue")['default']
  LightFooter: typeof import("../../components/light/Footer.vue")['default']
  LightHeader: typeof import("../../components/light/Header.vue")['default']
  LightHero: typeof import("../../components/light/Hero.vue")['default']
  LightServices: typeof import("../../components/light/Services.vue")['default']
  LightTeam: typeof import("../../components/light/Team.vue")['default']
  LightTestimonials: typeof import("../../components/light/Testimonials.vue")['default']
  LightWhyUs: typeof import("../../components/light/WhyUs.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyDarkEnAccreditations: LazyComponent<typeof import("../../components/dark-en/Accreditations.vue")['default']>
  LazyDarkEnBlog: LazyComponent<typeof import("../../components/dark-en/Blog.vue")['default']>
  LazyDarkEnCTA: LazyComponent<typeof import("../../components/dark-en/CTA.vue")['default']>
  LazyDarkEnFooter: LazyComponent<typeof import("../../components/dark-en/Footer.vue")['default']>
  LazyDarkEnHeader: LazyComponent<typeof import("../../components/dark-en/Header.vue")['default']>
  LazyDarkEnHero: LazyComponent<typeof import("../../components/dark-en/Hero.vue")['default']>
  LazyDarkEnServices: LazyComponent<typeof import("../../components/dark-en/Services.vue")['default']>
  LazyDarkEnTeam: LazyComponent<typeof import("../../components/dark-en/Team.vue")['default']>
  LazyDarkEnTestimonials: LazyComponent<typeof import("../../components/dark-en/Testimonials.vue")['default']>
  LazyDarkEnWhyUs: LazyComponent<typeof import("../../components/dark-en/WhyUs.vue")['default']>
  LazyDarkAccreditations: LazyComponent<typeof import("../../components/dark/Accreditations.vue")['default']>
  LazyDarkBlog: LazyComponent<typeof import("../../components/dark/Blog.vue")['default']>
  LazyDarkCTA: LazyComponent<typeof import("../../components/dark/CTA.vue")['default']>
  LazyDarkFooter: LazyComponent<typeof import("../../components/dark/Footer.vue")['default']>
  LazyDarkHeader: LazyComponent<typeof import("../../components/dark/Header.vue")['default']>
  LazyDarkHero: LazyComponent<typeof import("../../components/dark/Hero.vue")['default']>
  LazyDarkServices: LazyComponent<typeof import("../../components/dark/Services.vue")['default']>
  LazyDarkTeam: LazyComponent<typeof import("../../components/dark/Team.vue")['default']>
  LazyDarkTestimonials: LazyComponent<typeof import("../../components/dark/Testimonials.vue")['default']>
  LazyDarkWhyUs: LazyComponent<typeof import("../../components/dark/WhyUs.vue")['default']>
  LazyLanding2Accreditations: LazyComponent<typeof import("../../components/landing-2/Accreditations.vue")['default']>
  LazyLanding2AccreditationsEn: LazyComponent<typeof import("../../components/landing-2/AccreditationsEn.vue")['default']>
  LazyLanding2Blog: LazyComponent<typeof import("../../components/landing-2/Blog.vue")['default']>
  LazyLanding2BlogEn: LazyComponent<typeof import("../../components/landing-2/BlogEn.vue")['default']>
  LazyLanding2CTA: LazyComponent<typeof import("../../components/landing-2/CTA.vue")['default']>
  LazyLanding2CTAEn: LazyComponent<typeof import("../../components/landing-2/CTAEn.vue")['default']>
  LazyLanding2Footer: LazyComponent<typeof import("../../components/landing-2/Footer.vue")['default']>
  LazyLanding2FooterEn: LazyComponent<typeof import("../../components/landing-2/FooterEn.vue")['default']>
  LazyLanding2Header: LazyComponent<typeof import("../../components/landing-2/Header.vue")['default']>
  LazyLanding2HeaderEn: LazyComponent<typeof import("../../components/landing-2/HeaderEn.vue")['default']>
  LazyLanding2Hero: LazyComponent<typeof import("../../components/landing-2/Hero.vue")['default']>
  LazyLanding2HeroEn: LazyComponent<typeof import("../../components/landing-2/HeroEn.vue")['default']>
  LazyLanding2Services: LazyComponent<typeof import("../../components/landing-2/Services.vue")['default']>
  LazyLanding2ServicesEn: LazyComponent<typeof import("../../components/landing-2/ServicesEn.vue")['default']>
  LazyLanding2Team: LazyComponent<typeof import("../../components/landing-2/Team.vue")['default']>
  LazyLanding2TeamEn: LazyComponent<typeof import("../../components/landing-2/TeamEn.vue")['default']>
  LazyLanding2Testimonials: LazyComponent<typeof import("../../components/landing-2/Testimonials.vue")['default']>
  LazyLanding2TestimonialsEn: LazyComponent<typeof import("../../components/landing-2/TestimonialsEn.vue")['default']>
  LazyLanding2WhyUs: LazyComponent<typeof import("../../components/landing-2/WhyUs.vue")['default']>
  LazyLanding2WhyUsEn: LazyComponent<typeof import("../../components/landing-2/WhyUsEn.vue")['default']>
  LazyLanding3Accreditations: LazyComponent<typeof import("../../components/landing-3/Accreditations.vue")['default']>
  LazyLanding3AccreditationsEn: LazyComponent<typeof import("../../components/landing-3/AccreditationsEn.vue")['default']>
  LazyLanding3Blog: LazyComponent<typeof import("../../components/landing-3/Blog.vue")['default']>
  LazyLanding3BlogEn: LazyComponent<typeof import("../../components/landing-3/BlogEn.vue")['default']>
  LazyLanding3CTA: LazyComponent<typeof import("../../components/landing-3/CTA.vue")['default']>
  LazyLanding3CTAEn: LazyComponent<typeof import("../../components/landing-3/CTAEn.vue")['default']>
  LazyLanding3Footer: LazyComponent<typeof import("../../components/landing-3/Footer.vue")['default']>
  LazyLanding3FooterEn: LazyComponent<typeof import("../../components/landing-3/FooterEn.vue")['default']>
  LazyLanding3Header: LazyComponent<typeof import("../../components/landing-3/Header.vue")['default']>
  LazyLanding3HeaderEn: LazyComponent<typeof import("../../components/landing-3/HeaderEn.vue")['default']>
  LazyLanding3Hero: LazyComponent<typeof import("../../components/landing-3/Hero.vue")['default']>
  LazyLanding3HeroEn: LazyComponent<typeof import("../../components/landing-3/HeroEn.vue")['default']>
  LazyLanding3Services: LazyComponent<typeof import("../../components/landing-3/Services.vue")['default']>
  LazyLanding3ServicesEn: LazyComponent<typeof import("../../components/landing-3/ServicesEn.vue")['default']>
  LazyLanding3ServicesSlider: LazyComponent<typeof import("../../components/landing-3/ServicesSlider.vue")['default']>
  LazyLanding3ServicesSliderEn: LazyComponent<typeof import("../../components/landing-3/ServicesSliderEn.vue")['default']>
  LazyLanding3Team: LazyComponent<typeof import("../../components/landing-3/Team.vue")['default']>
  LazyLanding3TeamEn: LazyComponent<typeof import("../../components/landing-3/TeamEn.vue")['default']>
  LazyLanding3Testimonials: LazyComponent<typeof import("../../components/landing-3/Testimonials.vue")['default']>
  LazyLanding3TestimonialsEn: LazyComponent<typeof import("../../components/landing-3/TestimonialsEn.vue")['default']>
  LazyLanding3WhyUs: LazyComponent<typeof import("../../components/landing-3/WhyUs.vue")['default']>
  LazyLanding3WhyUsEn: LazyComponent<typeof import("../../components/landing-3/WhyUsEn.vue")['default']>
  LazyLanding4Accreditations: LazyComponent<typeof import("../../components/landing-4/Accreditations.vue")['default']>
  LazyLanding4AccreditationsEn: LazyComponent<typeof import("../../components/landing-4/AccreditationsEn.vue")['default']>
  LazyLanding4Blog: LazyComponent<typeof import("../../components/landing-4/Blog.vue")['default']>
  LazyLanding4BlogEn: LazyComponent<typeof import("../../components/landing-4/BlogEn.vue")['default']>
  LazyLanding4CTA: LazyComponent<typeof import("../../components/landing-4/CTA.vue")['default']>
  LazyLanding4CTAEn: LazyComponent<typeof import("../../components/landing-4/CTAEn.vue")['default']>
  LazyLanding4Footer: LazyComponent<typeof import("../../components/landing-4/Footer.vue")['default']>
  LazyLanding4FooterEn: LazyComponent<typeof import("../../components/landing-4/FooterEn.vue")['default']>
  LazyLanding4Header: LazyComponent<typeof import("../../components/landing-4/Header.vue")['default']>
  LazyLanding4HeaderEn: LazyComponent<typeof import("../../components/landing-4/HeaderEn.vue")['default']>
  LazyLanding4Hero: LazyComponent<typeof import("../../components/landing-4/Hero.vue")['default']>
  LazyLanding4HeroEn: LazyComponent<typeof import("../../components/landing-4/HeroEn.vue")['default']>
  LazyLanding4Services: LazyComponent<typeof import("../../components/landing-4/Services.vue")['default']>
  LazyLanding4ServicesEn: LazyComponent<typeof import("../../components/landing-4/ServicesEn.vue")['default']>
  LazyLanding4ServicesSlider: LazyComponent<typeof import("../../components/landing-4/ServicesSlider.vue")['default']>
  LazyLanding4ServicesSliderEn: LazyComponent<typeof import("../../components/landing-4/ServicesSliderEn.vue")['default']>
  LazyLanding4Team: LazyComponent<typeof import("../../components/landing-4/Team.vue")['default']>
  LazyLanding4TeamEn: LazyComponent<typeof import("../../components/landing-4/TeamEn.vue")['default']>
  LazyLanding4Testimonials: LazyComponent<typeof import("../../components/landing-4/Testimonials.vue")['default']>
  LazyLanding4TestimonialsEn: LazyComponent<typeof import("../../components/landing-4/TestimonialsEn.vue")['default']>
  LazyLanding4WhyUs: LazyComponent<typeof import("../../components/landing-4/WhyUs.vue")['default']>
  LazyLanding4WhyUsEn: LazyComponent<typeof import("../../components/landing-4/WhyUsEn.vue")['default']>
  LazyLightEnAccreditations: LazyComponent<typeof import("../../components/light-en/Accreditations.vue")['default']>
  LazyLightEnBlog: LazyComponent<typeof import("../../components/light-en/Blog.vue")['default']>
  LazyLightEnCTA: LazyComponent<typeof import("../../components/light-en/CTA.vue")['default']>
  LazyLightEnFooter: LazyComponent<typeof import("../../components/light-en/Footer.vue")['default']>
  LazyLightEnHeader: LazyComponent<typeof import("../../components/light-en/Header.vue")['default']>
  LazyLightEnHero: LazyComponent<typeof import("../../components/light-en/Hero.vue")['default']>
  LazyLightEnServices: LazyComponent<typeof import("../../components/light-en/Services.vue")['default']>
  LazyLightEnTeam: LazyComponent<typeof import("../../components/light-en/Team.vue")['default']>
  LazyLightEnTestimonials: LazyComponent<typeof import("../../components/light-en/Testimonials.vue")['default']>
  LazyLightEnWhyUs: LazyComponent<typeof import("../../components/light-en/WhyUs.vue")['default']>
  LazyLightAccreditations: LazyComponent<typeof import("../../components/light/Accreditations.vue")['default']>
  LazyLightBlog: LazyComponent<typeof import("../../components/light/Blog.vue")['default']>
  LazyLightCTA: LazyComponent<typeof import("../../components/light/CTA.vue")['default']>
  LazyLightFooter: LazyComponent<typeof import("../../components/light/Footer.vue")['default']>
  LazyLightHeader: LazyComponent<typeof import("../../components/light/Header.vue")['default']>
  LazyLightHero: LazyComponent<typeof import("../../components/light/Hero.vue")['default']>
  LazyLightServices: LazyComponent<typeof import("../../components/light/Services.vue")['default']>
  LazyLightTeam: LazyComponent<typeof import("../../components/light/Team.vue")['default']>
  LazyLightTestimonials: LazyComponent<typeof import("../../components/light/Testimonials.vue")['default']>
  LazyLightWhyUs: LazyComponent<typeof import("../../components/light/WhyUs.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
