
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const About1HeroAr: typeof import("../components/about-1/HeroAr.vue")['default']
export const About1HeroEn: typeof import("../components/about-1/HeroEn.vue")['default']
export const About1MissionAr: typeof import("../components/about-1/MissionAr.vue")['default']
export const About1MissionEn: typeof import("../components/about-1/MissionEn.vue")['default']
export const About1WhyUsAr: typeof import("../components/about-1/WhyUsAr.vue")['default']
export const About1WhyUsEn: typeof import("../components/about-1/WhyUsEn.vue")['default']
export const About2HeroAr: typeof import("../components/about-2/HeroAr.vue")['default']
export const About2HeroEn: typeof import("../components/about-2/HeroEn.vue")['default']
export const About3HeroAr: typeof import("../components/about-3/HeroAr.vue")['default']
export const About3HeroEn: typeof import("../components/about-3/HeroEn.vue")['default']
export const About3WhyUsAr: typeof import("../components/about-3/WhyUsAr.vue")['default']
export const About3WhyUsEn: typeof import("../components/about-3/WhyUsEn.vue")['default']
export const About4HeroAr: typeof import("../components/about-4/HeroAr.vue")['default']
export const About4HeroEn: typeof import("../components/about-4/HeroEn.vue")['default']
export const About4MissionAr: typeof import("../components/about-4/MissionAr.vue")['default']
export const About4MissionEn: typeof import("../components/about-4/MissionEn.vue")['default']
export const About4WhyUsAr: typeof import("../components/about-4/WhyUsAr.vue")['default']
export const About4WhyUsEn: typeof import("../components/about-4/WhyUsEn.vue")['default']
export const About5HeaderAr: typeof import("../components/about-5/HeaderAr.vue")['default']
export const About5HeaderEn: typeof import("../components/about-5/HeaderEn.vue")['default']
export const About5HeroAr: typeof import("../components/about-5/HeroAr.vue")['default']
export const About5HeroEn: typeof import("../components/about-5/HeroEn.vue")['default']
export const About5MissionAr: typeof import("../components/about-5/MissionAr.vue")['default']
export const About5MissionEn: typeof import("../components/about-5/MissionEn.vue")['default']
export const About5WhyUsAr: typeof import("../components/about-5/WhyUsAr.vue")['default']
export const About5WhyUsEn: typeof import("../components/about-5/WhyUsEn.vue")['default']
export const DarkEnAccreditations: typeof import("../components/dark-en/Accreditations.vue")['default']
export const DarkEnBlog: typeof import("../components/dark-en/Blog.vue")['default']
export const DarkEnCTA: typeof import("../components/dark-en/CTA.vue")['default']
export const DarkEnFooter: typeof import("../components/dark-en/Footer.vue")['default']
export const DarkEnHeader: typeof import("../components/dark-en/Header.vue")['default']
export const DarkEnHero: typeof import("../components/dark-en/Hero.vue")['default']
export const DarkEnServices: typeof import("../components/dark-en/Services.vue")['default']
export const DarkEnTeam: typeof import("../components/dark-en/Team.vue")['default']
export const DarkEnTestimonials: typeof import("../components/dark-en/Testimonials.vue")['default']
export const DarkEnWhyUs: typeof import("../components/dark-en/WhyUs.vue")['default']
export const DarkAccreditations: typeof import("../components/dark/Accreditations.vue")['default']
export const DarkBlog: typeof import("../components/dark/Blog.vue")['default']
export const DarkCTA: typeof import("../components/dark/CTA.vue")['default']
export const DarkFooter: typeof import("../components/dark/Footer.vue")['default']
export const DarkHeader: typeof import("../components/dark/Header.vue")['default']
export const DarkHero: typeof import("../components/dark/Hero.vue")['default']
export const DarkServices: typeof import("../components/dark/Services.vue")['default']
export const DarkTeam: typeof import("../components/dark/Team.vue")['default']
export const DarkTestimonials: typeof import("../components/dark/Testimonials.vue")['default']
export const DarkWhyUs: typeof import("../components/dark/WhyUs.vue")['default']
export const Landing2Accreditations: typeof import("../components/landing-2/Accreditations.vue")['default']
export const Landing2AccreditationsEn: typeof import("../components/landing-2/AccreditationsEn.vue")['default']
export const Landing2Blog: typeof import("../components/landing-2/Blog.vue")['default']
export const Landing2BlogEn: typeof import("../components/landing-2/BlogEn.vue")['default']
export const Landing2CTA: typeof import("../components/landing-2/CTA.vue")['default']
export const Landing2CTAEn: typeof import("../components/landing-2/CTAEn.vue")['default']
export const Landing2Footer: typeof import("../components/landing-2/Footer.vue")['default']
export const Landing2FooterEn: typeof import("../components/landing-2/FooterEn.vue")['default']
export const Landing2Header: typeof import("../components/landing-2/Header.vue")['default']
export const Landing2HeaderEn: typeof import("../components/landing-2/HeaderEn.vue")['default']
export const Landing2Hero: typeof import("../components/landing-2/Hero.vue")['default']
export const Landing2HeroEn: typeof import("../components/landing-2/HeroEn.vue")['default']
export const Landing2Services: typeof import("../components/landing-2/Services.vue")['default']
export const Landing2ServicesEn: typeof import("../components/landing-2/ServicesEn.vue")['default']
export const Landing2Team: typeof import("../components/landing-2/Team.vue")['default']
export const Landing2TeamEn: typeof import("../components/landing-2/TeamEn.vue")['default']
export const Landing2Testimonials: typeof import("../components/landing-2/Testimonials.vue")['default']
export const Landing2TestimonialsEn: typeof import("../components/landing-2/TestimonialsEn.vue")['default']
export const Landing2WhyUs: typeof import("../components/landing-2/WhyUs.vue")['default']
export const Landing2WhyUsEn: typeof import("../components/landing-2/WhyUsEn.vue")['default']
export const Landing3Accreditations: typeof import("../components/landing-3/Accreditations.vue")['default']
export const Landing3AccreditationsEn: typeof import("../components/landing-3/AccreditationsEn.vue")['default']
export const Landing3Blog: typeof import("../components/landing-3/Blog.vue")['default']
export const Landing3BlogEn: typeof import("../components/landing-3/BlogEn.vue")['default']
export const Landing3CTA: typeof import("../components/landing-3/CTA.vue")['default']
export const Landing3CTAEn: typeof import("../components/landing-3/CTAEn.vue")['default']
export const Landing3Footer: typeof import("../components/landing-3/Footer.vue")['default']
export const Landing3FooterEn: typeof import("../components/landing-3/FooterEn.vue")['default']
export const Landing3Header: typeof import("../components/landing-3/Header.vue")['default']
export const Landing3HeaderEn: typeof import("../components/landing-3/HeaderEn.vue")['default']
export const Landing3Hero: typeof import("../components/landing-3/Hero.vue")['default']
export const Landing3HeroEn: typeof import("../components/landing-3/HeroEn.vue")['default']
export const Landing3Services: typeof import("../components/landing-3/Services.vue")['default']
export const Landing3ServicesEn: typeof import("../components/landing-3/ServicesEn.vue")['default']
export const Landing3ServicesSlider: typeof import("../components/landing-3/ServicesSlider.vue")['default']
export const Landing3ServicesSliderEn: typeof import("../components/landing-3/ServicesSliderEn.vue")['default']
export const Landing3Team: typeof import("../components/landing-3/Team.vue")['default']
export const Landing3TeamEn: typeof import("../components/landing-3/TeamEn.vue")['default']
export const Landing3Testimonials: typeof import("../components/landing-3/Testimonials.vue")['default']
export const Landing3TestimonialsEn: typeof import("../components/landing-3/TestimonialsEn.vue")['default']
export const Landing3WhyUs: typeof import("../components/landing-3/WhyUs.vue")['default']
export const Landing3WhyUsEn: typeof import("../components/landing-3/WhyUsEn.vue")['default']
export const Landing4Accreditations: typeof import("../components/landing-4/Accreditations.vue")['default']
export const Landing4AccreditationsEn: typeof import("../components/landing-4/AccreditationsEn.vue")['default']
export const Landing4Blog: typeof import("../components/landing-4/Blog.vue")['default']
export const Landing4BlogEn: typeof import("../components/landing-4/BlogEn.vue")['default']
export const Landing4CTA: typeof import("../components/landing-4/CTA.vue")['default']
export const Landing4CTAEn: typeof import("../components/landing-4/CTAEn.vue")['default']
export const Landing4Footer: typeof import("../components/landing-4/Footer.vue")['default']
export const Landing4FooterEn: typeof import("../components/landing-4/FooterEn.vue")['default']
export const Landing4Header: typeof import("../components/landing-4/Header.vue")['default']
export const Landing4HeaderEn: typeof import("../components/landing-4/HeaderEn.vue")['default']
export const Landing4Hero: typeof import("../components/landing-4/Hero.vue")['default']
export const Landing4HeroEn: typeof import("../components/landing-4/HeroEn.vue")['default']
export const Landing4Services: typeof import("../components/landing-4/Services.vue")['default']
export const Landing4ServicesEn: typeof import("../components/landing-4/ServicesEn.vue")['default']
export const Landing4ServicesSlider: typeof import("../components/landing-4/ServicesSlider.vue")['default']
export const Landing4ServicesSliderEn: typeof import("../components/landing-4/ServicesSliderEn.vue")['default']
export const Landing4Team: typeof import("../components/landing-4/Team.vue")['default']
export const Landing4TeamEn: typeof import("../components/landing-4/TeamEn.vue")['default']
export const Landing4Testimonials: typeof import("../components/landing-4/Testimonials.vue")['default']
export const Landing4TestimonialsEn: typeof import("../components/landing-4/TestimonialsEn.vue")['default']
export const Landing4WhyUs: typeof import("../components/landing-4/WhyUs.vue")['default']
export const Landing4WhyUsEn: typeof import("../components/landing-4/WhyUsEn.vue")['default']
export const LawyerDetails1BreadcrumbAr: typeof import("../components/lawyer-details-1/BreadcrumbAr.vue")['default']
export const LawyerDetails1BreadcrumbEn: typeof import("../components/lawyer-details-1/BreadcrumbEn.vue")['default']
export const LawyerDetails1CTAAr: typeof import("../components/lawyer-details-1/CTAAr.vue")['default']
export const LawyerDetails1CTAEn: typeof import("../components/lawyer-details-1/CTAEn.vue")['default']
export const LawyerDetails1FooterAr: typeof import("../components/lawyer-details-1/FooterAr.vue")['default']
export const LawyerDetails1FooterEn: typeof import("../components/lawyer-details-1/FooterEn.vue")['default']
export const LawyerDetails1HeroAr: typeof import("../components/lawyer-details-1/HeroAr.vue")['default']
export const LawyerDetails1HeroEn: typeof import("../components/lawyer-details-1/HeroEn.vue")['default']
export const LawyerDetails1LawyerDetailsAr: typeof import("../components/lawyer-details-1/LawyerDetailsAr.vue")['default']
export const LawyerDetails1LawyerDetailsEn: typeof import("../components/lawyer-details-1/LawyerDetailsEn.vue")['default']
export const LawyerDetails1LawyerProfileAr: typeof import("../components/lawyer-details-1/LawyerProfileAr.vue")['default']
export const LawyerDetails1LawyerProfileEn: typeof import("../components/lawyer-details-1/LawyerProfileEn.vue")['default']
export const LawyerDetails1TeamGridAr: typeof import("../components/lawyer-details-1/TeamGridAr.vue")['default']
export const LawyerDetails1TeamGridEn: typeof import("../components/lawyer-details-1/TeamGridEn.vue")['default']
export const LawyerDetails2BreadcrumbAr: typeof import("../components/lawyer-details-2/BreadcrumbAr.vue")['default']
export const LawyerDetails2BreadcrumbEn: typeof import("../components/lawyer-details-2/BreadcrumbEn.vue")['default']
export const LawyerDetails2CTAAr: typeof import("../components/lawyer-details-2/CTAAr.vue")['default']
export const LawyerDetails2CTAEn: typeof import("../components/lawyer-details-2/CTAEn.vue")['default']
export const LawyerDetails2FooterAr: typeof import("../components/lawyer-details-2/FooterAr.vue")['default']
export const LawyerDetails2FooterEn: typeof import("../components/lawyer-details-2/FooterEn.vue")['default']
export const LawyerDetails2HeroAr: typeof import("../components/lawyer-details-2/HeroAr.vue")['default']
export const LawyerDetails2HeroEn: typeof import("../components/lawyer-details-2/HeroEn.vue")['default']
export const LawyerDetails2LawyerDetailsAr: typeof import("../components/lawyer-details-2/LawyerDetailsAr.vue")['default']
export const LawyerDetails2LawyerDetailsEn: typeof import("../components/lawyer-details-2/LawyerDetailsEn.vue")['default']
export const LawyerDetails2LawyerProfileAr: typeof import("../components/lawyer-details-2/LawyerProfileAr.vue")['default']
export const LawyerDetails2LawyerProfileEn: typeof import("../components/lawyer-details-2/LawyerProfileEn.vue")['default']
export const LawyerDetails2TeamGridAr: typeof import("../components/lawyer-details-2/TeamGridAr.vue")['default']
export const LawyerDetails2TeamGridEn: typeof import("../components/lawyer-details-2/TeamGridEn.vue")['default']
export const LawyerDetails3BreadcrumbAr: typeof import("../components/lawyer-details-3/BreadcrumbAr.vue")['default']
export const LawyerDetails3BreadcrumbEn: typeof import("../components/lawyer-details-3/BreadcrumbEn.vue")['default']
export const LawyerDetails3CTAAr: typeof import("../components/lawyer-details-3/CTAAr.vue")['default']
export const LawyerDetails3CTAEn: typeof import("../components/lawyer-details-3/CTAEn.vue")['default']
export const LawyerDetails3FooterAr: typeof import("../components/lawyer-details-3/FooterAr.vue")['default']
export const LawyerDetails3FooterEn: typeof import("../components/lawyer-details-3/FooterEn.vue")['default']
export const LawyerDetails3HeroAr: typeof import("../components/lawyer-details-3/HeroAr.vue")['default']
export const LawyerDetails3HeroEn: typeof import("../components/lawyer-details-3/HeroEn.vue")['default']
export const LawyerDetails3LawyerDetailsAr: typeof import("../components/lawyer-details-3/LawyerDetailsAr.vue")['default']
export const LawyerDetails3LawyerDetailsEn: typeof import("../components/lawyer-details-3/LawyerDetailsEn.vue")['default']
export const LawyerDetails3LawyerProfileAr: typeof import("../components/lawyer-details-3/LawyerProfileAr.vue")['default']
export const LawyerDetails3LawyerProfileEn: typeof import("../components/lawyer-details-3/LawyerProfileEn.vue")['default']
export const LawyerDetails3TeamGridAr: typeof import("../components/lawyer-details-3/TeamGridAr.vue")['default']
export const LawyerDetails3TeamGridEn: typeof import("../components/lawyer-details-3/TeamGridEn.vue")['default']
export const LightEnAccreditations: typeof import("../components/light-en/Accreditations.vue")['default']
export const LightEnBlog: typeof import("../components/light-en/Blog.vue")['default']
export const LightEnCTA: typeof import("../components/light-en/CTA.vue")['default']
export const LightEnFooter: typeof import("../components/light-en/Footer.vue")['default']
export const LightEnHeader: typeof import("../components/light-en/Header.vue")['default']
export const LightEnHero: typeof import("../components/light-en/Hero.vue")['default']
export const LightEnServices: typeof import("../components/light-en/Services.vue")['default']
export const LightEnTeam: typeof import("../components/light-en/Team.vue")['default']
export const LightEnTestimonials: typeof import("../components/light-en/Testimonials.vue")['default']
export const LightEnWhyUs: typeof import("../components/light-en/WhyUs.vue")['default']
export const LightAccreditations: typeof import("../components/light/Accreditations.vue")['default']
export const LightBlog: typeof import("../components/light/Blog.vue")['default']
export const LightCTA: typeof import("../components/light/CTA.vue")['default']
export const LightFooter: typeof import("../components/light/Footer.vue")['default']
export const LightHeader: typeof import("../components/light/Header.vue")['default']
export const LightHero: typeof import("../components/light/Hero.vue")['default']
export const LightServices: typeof import("../components/light/Services.vue")['default']
export const LightTeam: typeof import("../components/light/Team.vue")['default']
export const LightTestimonials: typeof import("../components/light/Testimonials.vue")['default']
export const LightWhyUs: typeof import("../components/light/WhyUs.vue")['default']
export const Services1BreadcrumbAr: typeof import("../components/services-1/BreadcrumbAr.vue")['default']
export const Services1BreadcrumbEn: typeof import("../components/services-1/BreadcrumbEn.vue")['default']
export const Services1CTAAr: typeof import("../components/services-1/CTAAr.vue")['default']
export const Services1CTAEn: typeof import("../components/services-1/CTAEn.vue")['default']
export const Services1HeroAr: typeof import("../components/services-1/HeroAr.vue")['default']
export const Services1HeroEn: typeof import("../components/services-1/HeroEn.vue")['default']
export const Services1ServicesListAr: typeof import("../components/services-1/ServicesListAr.vue")['default']
export const Services1ServicesListEn: typeof import("../components/services-1/ServicesListEn.vue")['default']
export const Services2CTAAr: typeof import("../components/services-2/CTAAr.vue")['default']
export const Services2CTAEn: typeof import("../components/services-2/CTAEn.vue")['default']
export const Services2FooterAr: typeof import("../components/services-2/FooterAr.vue")['default']
export const Services2FooterEn: typeof import("../components/services-2/FooterEn.vue")['default']
export const Services2ServicesGridAr: typeof import("../components/services-2/ServicesGridAr.vue")['default']
export const Services2ServicesGridEn: typeof import("../components/services-2/ServicesGridEn.vue")['default']
export const Services3CTAAr: typeof import("../components/services-3/CTAAr.vue")['default']
export const Services3CTAEn: typeof import("../components/services-3/CTAEn.vue")['default']
export const Services3FooterAr: typeof import("../components/services-3/FooterAr.vue")['default']
export const Services3FooterEn: typeof import("../components/services-3/FooterEn.vue")['default']
export const Services3ServicesGridAr: typeof import("../components/services-3/ServicesGridAr.vue")['default']
export const Services3ServicesGridEn: typeof import("../components/services-3/ServicesGridEn.vue")['default']
export const Services4CTAAr: typeof import("../components/services-4/CTAAr.vue")['default']
export const Services4CTAEn: typeof import("../components/services-4/CTAEn.vue")['default']
export const Services4FooterAr: typeof import("../components/services-4/FooterAr.vue")['default']
export const Services4FooterEn: typeof import("../components/services-4/FooterEn.vue")['default']
export const Services4ServicesGridAr: typeof import("../components/services-4/ServicesGridAr.vue")['default']
export const Services4ServicesGridEn: typeof import("../components/services-4/ServicesGridEn.vue")['default']
export const Services5CTAAr: typeof import("../components/services-5/CTAAr.vue")['default']
export const Services5CTAEn: typeof import("../components/services-5/CTAEn.vue")['default']
export const Services5FooterAr: typeof import("../components/services-5/FooterAr.vue")['default']
export const Services5FooterEn: typeof import("../components/services-5/FooterEn.vue")['default']
export const Services5ServicesGridAr: typeof import("../components/services-5/ServicesGridAr.vue")['default']
export const Services5ServicesGridEn: typeof import("../components/services-5/ServicesGridEn.vue")['default']
export const SharedLanding4HeaderAr: typeof import("../components/shared-landing-4/HeaderAr.vue")['default']
export const SharedLanding4HeaderEn: typeof import("../components/shared-landing-4/HeaderEn.vue")['default']
export const SharedLanding4HeroAr: typeof import("../components/shared-landing-4/HeroAr.vue")['default']
export const SharedLanding4HeroEn: typeof import("../components/shared-landing-4/HeroEn.vue")['default']
export const Team1CTAAr: typeof import("../components/team-1/CTAAr.vue")['default']
export const Team1CTAEn: typeof import("../components/team-1/CTAEn.vue")['default']
export const Team1FooterAr: typeof import("../components/team-1/FooterAr.vue")['default']
export const Team1FooterEn: typeof import("../components/team-1/FooterEn.vue")['default']
export const Team1HeroAr: typeof import("../components/team-1/HeroAr.vue")['default']
export const Team1HeroEn: typeof import("../components/team-1/HeroEn.vue")['default']
export const Team1TeamGridAr: typeof import("../components/team-1/TeamGridAr.vue")['default']
export const Team1TeamGridEn: typeof import("../components/team-1/TeamGridEn.vue")['default']
export const Team2CTAAr: typeof import("../components/team-2/CTAAr.vue")['default']
export const Team2CTAEn: typeof import("../components/team-2/CTAEn.vue")['default']
export const Team2FooterAr: typeof import("../components/team-2/FooterAr.vue")['default']
export const Team2FooterEn: typeof import("../components/team-2/FooterEn.vue")['default']
export const Team2HeroAr: typeof import("../components/team-2/HeroAr.vue")['default']
export const Team2HeroEn: typeof import("../components/team-2/HeroEn.vue")['default']
export const Team2TeamGridAr: typeof import("../components/team-2/TeamGridAr.vue")['default']
export const Team2TeamGridEn: typeof import("../components/team-2/TeamGridEn.vue")['default']
export const Team3CTAAr: typeof import("../components/team-3/CTAAr.vue")['default']
export const Team3CTAEn: typeof import("../components/team-3/CTAEn.vue")['default']
export const Team3FooterAr: typeof import("../components/team-3/FooterAr.vue")['default']
export const Team3FooterEn: typeof import("../components/team-3/FooterEn.vue")['default']
export const Team3HeaderAr: typeof import("../components/team-3/HeaderAr.vue")['default']
export const Team3HeaderEn: typeof import("../components/team-3/HeaderEn.vue")['default']
export const Team3HeroAr: typeof import("../components/team-3/HeroAr.vue")['default']
export const Team3HeroEn: typeof import("../components/team-3/HeroEn.vue")['default']
export const Team3TeamGridAr: typeof import("../components/team-3/TeamGridAr.vue")['default']
export const Team3TeamGridEn: typeof import("../components/team-3/TeamGridEn.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAbout1HeroAr: LazyComponent<typeof import("../components/about-1/HeroAr.vue")['default']>
export const LazyAbout1HeroEn: LazyComponent<typeof import("../components/about-1/HeroEn.vue")['default']>
export const LazyAbout1MissionAr: LazyComponent<typeof import("../components/about-1/MissionAr.vue")['default']>
export const LazyAbout1MissionEn: LazyComponent<typeof import("../components/about-1/MissionEn.vue")['default']>
export const LazyAbout1WhyUsAr: LazyComponent<typeof import("../components/about-1/WhyUsAr.vue")['default']>
export const LazyAbout1WhyUsEn: LazyComponent<typeof import("../components/about-1/WhyUsEn.vue")['default']>
export const LazyAbout2HeroAr: LazyComponent<typeof import("../components/about-2/HeroAr.vue")['default']>
export const LazyAbout2HeroEn: LazyComponent<typeof import("../components/about-2/HeroEn.vue")['default']>
export const LazyAbout3HeroAr: LazyComponent<typeof import("../components/about-3/HeroAr.vue")['default']>
export const LazyAbout3HeroEn: LazyComponent<typeof import("../components/about-3/HeroEn.vue")['default']>
export const LazyAbout3WhyUsAr: LazyComponent<typeof import("../components/about-3/WhyUsAr.vue")['default']>
export const LazyAbout3WhyUsEn: LazyComponent<typeof import("../components/about-3/WhyUsEn.vue")['default']>
export const LazyAbout4HeroAr: LazyComponent<typeof import("../components/about-4/HeroAr.vue")['default']>
export const LazyAbout4HeroEn: LazyComponent<typeof import("../components/about-4/HeroEn.vue")['default']>
export const LazyAbout4MissionAr: LazyComponent<typeof import("../components/about-4/MissionAr.vue")['default']>
export const LazyAbout4MissionEn: LazyComponent<typeof import("../components/about-4/MissionEn.vue")['default']>
export const LazyAbout4WhyUsAr: LazyComponent<typeof import("../components/about-4/WhyUsAr.vue")['default']>
export const LazyAbout4WhyUsEn: LazyComponent<typeof import("../components/about-4/WhyUsEn.vue")['default']>
export const LazyAbout5HeaderAr: LazyComponent<typeof import("../components/about-5/HeaderAr.vue")['default']>
export const LazyAbout5HeaderEn: LazyComponent<typeof import("../components/about-5/HeaderEn.vue")['default']>
export const LazyAbout5HeroAr: LazyComponent<typeof import("../components/about-5/HeroAr.vue")['default']>
export const LazyAbout5HeroEn: LazyComponent<typeof import("../components/about-5/HeroEn.vue")['default']>
export const LazyAbout5MissionAr: LazyComponent<typeof import("../components/about-5/MissionAr.vue")['default']>
export const LazyAbout5MissionEn: LazyComponent<typeof import("../components/about-5/MissionEn.vue")['default']>
export const LazyAbout5WhyUsAr: LazyComponent<typeof import("../components/about-5/WhyUsAr.vue")['default']>
export const LazyAbout5WhyUsEn: LazyComponent<typeof import("../components/about-5/WhyUsEn.vue")['default']>
export const LazyDarkEnAccreditations: LazyComponent<typeof import("../components/dark-en/Accreditations.vue")['default']>
export const LazyDarkEnBlog: LazyComponent<typeof import("../components/dark-en/Blog.vue")['default']>
export const LazyDarkEnCTA: LazyComponent<typeof import("../components/dark-en/CTA.vue")['default']>
export const LazyDarkEnFooter: LazyComponent<typeof import("../components/dark-en/Footer.vue")['default']>
export const LazyDarkEnHeader: LazyComponent<typeof import("../components/dark-en/Header.vue")['default']>
export const LazyDarkEnHero: LazyComponent<typeof import("../components/dark-en/Hero.vue")['default']>
export const LazyDarkEnServices: LazyComponent<typeof import("../components/dark-en/Services.vue")['default']>
export const LazyDarkEnTeam: LazyComponent<typeof import("../components/dark-en/Team.vue")['default']>
export const LazyDarkEnTestimonials: LazyComponent<typeof import("../components/dark-en/Testimonials.vue")['default']>
export const LazyDarkEnWhyUs: LazyComponent<typeof import("../components/dark-en/WhyUs.vue")['default']>
export const LazyDarkAccreditations: LazyComponent<typeof import("../components/dark/Accreditations.vue")['default']>
export const LazyDarkBlog: LazyComponent<typeof import("../components/dark/Blog.vue")['default']>
export const LazyDarkCTA: LazyComponent<typeof import("../components/dark/CTA.vue")['default']>
export const LazyDarkFooter: LazyComponent<typeof import("../components/dark/Footer.vue")['default']>
export const LazyDarkHeader: LazyComponent<typeof import("../components/dark/Header.vue")['default']>
export const LazyDarkHero: LazyComponent<typeof import("../components/dark/Hero.vue")['default']>
export const LazyDarkServices: LazyComponent<typeof import("../components/dark/Services.vue")['default']>
export const LazyDarkTeam: LazyComponent<typeof import("../components/dark/Team.vue")['default']>
export const LazyDarkTestimonials: LazyComponent<typeof import("../components/dark/Testimonials.vue")['default']>
export const LazyDarkWhyUs: LazyComponent<typeof import("../components/dark/WhyUs.vue")['default']>
export const LazyLanding2Accreditations: LazyComponent<typeof import("../components/landing-2/Accreditations.vue")['default']>
export const LazyLanding2AccreditationsEn: LazyComponent<typeof import("../components/landing-2/AccreditationsEn.vue")['default']>
export const LazyLanding2Blog: LazyComponent<typeof import("../components/landing-2/Blog.vue")['default']>
export const LazyLanding2BlogEn: LazyComponent<typeof import("../components/landing-2/BlogEn.vue")['default']>
export const LazyLanding2CTA: LazyComponent<typeof import("../components/landing-2/CTA.vue")['default']>
export const LazyLanding2CTAEn: LazyComponent<typeof import("../components/landing-2/CTAEn.vue")['default']>
export const LazyLanding2Footer: LazyComponent<typeof import("../components/landing-2/Footer.vue")['default']>
export const LazyLanding2FooterEn: LazyComponent<typeof import("../components/landing-2/FooterEn.vue")['default']>
export const LazyLanding2Header: LazyComponent<typeof import("../components/landing-2/Header.vue")['default']>
export const LazyLanding2HeaderEn: LazyComponent<typeof import("../components/landing-2/HeaderEn.vue")['default']>
export const LazyLanding2Hero: LazyComponent<typeof import("../components/landing-2/Hero.vue")['default']>
export const LazyLanding2HeroEn: LazyComponent<typeof import("../components/landing-2/HeroEn.vue")['default']>
export const LazyLanding2Services: LazyComponent<typeof import("../components/landing-2/Services.vue")['default']>
export const LazyLanding2ServicesEn: LazyComponent<typeof import("../components/landing-2/ServicesEn.vue")['default']>
export const LazyLanding2Team: LazyComponent<typeof import("../components/landing-2/Team.vue")['default']>
export const LazyLanding2TeamEn: LazyComponent<typeof import("../components/landing-2/TeamEn.vue")['default']>
export const LazyLanding2Testimonials: LazyComponent<typeof import("../components/landing-2/Testimonials.vue")['default']>
export const LazyLanding2TestimonialsEn: LazyComponent<typeof import("../components/landing-2/TestimonialsEn.vue")['default']>
export const LazyLanding2WhyUs: LazyComponent<typeof import("../components/landing-2/WhyUs.vue")['default']>
export const LazyLanding2WhyUsEn: LazyComponent<typeof import("../components/landing-2/WhyUsEn.vue")['default']>
export const LazyLanding3Accreditations: LazyComponent<typeof import("../components/landing-3/Accreditations.vue")['default']>
export const LazyLanding3AccreditationsEn: LazyComponent<typeof import("../components/landing-3/AccreditationsEn.vue")['default']>
export const LazyLanding3Blog: LazyComponent<typeof import("../components/landing-3/Blog.vue")['default']>
export const LazyLanding3BlogEn: LazyComponent<typeof import("../components/landing-3/BlogEn.vue")['default']>
export const LazyLanding3CTA: LazyComponent<typeof import("../components/landing-3/CTA.vue")['default']>
export const LazyLanding3CTAEn: LazyComponent<typeof import("../components/landing-3/CTAEn.vue")['default']>
export const LazyLanding3Footer: LazyComponent<typeof import("../components/landing-3/Footer.vue")['default']>
export const LazyLanding3FooterEn: LazyComponent<typeof import("../components/landing-3/FooterEn.vue")['default']>
export const LazyLanding3Header: LazyComponent<typeof import("../components/landing-3/Header.vue")['default']>
export const LazyLanding3HeaderEn: LazyComponent<typeof import("../components/landing-3/HeaderEn.vue")['default']>
export const LazyLanding3Hero: LazyComponent<typeof import("../components/landing-3/Hero.vue")['default']>
export const LazyLanding3HeroEn: LazyComponent<typeof import("../components/landing-3/HeroEn.vue")['default']>
export const LazyLanding3Services: LazyComponent<typeof import("../components/landing-3/Services.vue")['default']>
export const LazyLanding3ServicesEn: LazyComponent<typeof import("../components/landing-3/ServicesEn.vue")['default']>
export const LazyLanding3ServicesSlider: LazyComponent<typeof import("../components/landing-3/ServicesSlider.vue")['default']>
export const LazyLanding3ServicesSliderEn: LazyComponent<typeof import("../components/landing-3/ServicesSliderEn.vue")['default']>
export const LazyLanding3Team: LazyComponent<typeof import("../components/landing-3/Team.vue")['default']>
export const LazyLanding3TeamEn: LazyComponent<typeof import("../components/landing-3/TeamEn.vue")['default']>
export const LazyLanding3Testimonials: LazyComponent<typeof import("../components/landing-3/Testimonials.vue")['default']>
export const LazyLanding3TestimonialsEn: LazyComponent<typeof import("../components/landing-3/TestimonialsEn.vue")['default']>
export const LazyLanding3WhyUs: LazyComponent<typeof import("../components/landing-3/WhyUs.vue")['default']>
export const LazyLanding3WhyUsEn: LazyComponent<typeof import("../components/landing-3/WhyUsEn.vue")['default']>
export const LazyLanding4Accreditations: LazyComponent<typeof import("../components/landing-4/Accreditations.vue")['default']>
export const LazyLanding4AccreditationsEn: LazyComponent<typeof import("../components/landing-4/AccreditationsEn.vue")['default']>
export const LazyLanding4Blog: LazyComponent<typeof import("../components/landing-4/Blog.vue")['default']>
export const LazyLanding4BlogEn: LazyComponent<typeof import("../components/landing-4/BlogEn.vue")['default']>
export const LazyLanding4CTA: LazyComponent<typeof import("../components/landing-4/CTA.vue")['default']>
export const LazyLanding4CTAEn: LazyComponent<typeof import("../components/landing-4/CTAEn.vue")['default']>
export const LazyLanding4Footer: LazyComponent<typeof import("../components/landing-4/Footer.vue")['default']>
export const LazyLanding4FooterEn: LazyComponent<typeof import("../components/landing-4/FooterEn.vue")['default']>
export const LazyLanding4Header: LazyComponent<typeof import("../components/landing-4/Header.vue")['default']>
export const LazyLanding4HeaderEn: LazyComponent<typeof import("../components/landing-4/HeaderEn.vue")['default']>
export const LazyLanding4Hero: LazyComponent<typeof import("../components/landing-4/Hero.vue")['default']>
export const LazyLanding4HeroEn: LazyComponent<typeof import("../components/landing-4/HeroEn.vue")['default']>
export const LazyLanding4Services: LazyComponent<typeof import("../components/landing-4/Services.vue")['default']>
export const LazyLanding4ServicesEn: LazyComponent<typeof import("../components/landing-4/ServicesEn.vue")['default']>
export const LazyLanding4ServicesSlider: LazyComponent<typeof import("../components/landing-4/ServicesSlider.vue")['default']>
export const LazyLanding4ServicesSliderEn: LazyComponent<typeof import("../components/landing-4/ServicesSliderEn.vue")['default']>
export const LazyLanding4Team: LazyComponent<typeof import("../components/landing-4/Team.vue")['default']>
export const LazyLanding4TeamEn: LazyComponent<typeof import("../components/landing-4/TeamEn.vue")['default']>
export const LazyLanding4Testimonials: LazyComponent<typeof import("../components/landing-4/Testimonials.vue")['default']>
export const LazyLanding4TestimonialsEn: LazyComponent<typeof import("../components/landing-4/TestimonialsEn.vue")['default']>
export const LazyLanding4WhyUs: LazyComponent<typeof import("../components/landing-4/WhyUs.vue")['default']>
export const LazyLanding4WhyUsEn: LazyComponent<typeof import("../components/landing-4/WhyUsEn.vue")['default']>
export const LazyLawyerDetails1BreadcrumbAr: LazyComponent<typeof import("../components/lawyer-details-1/BreadcrumbAr.vue")['default']>
export const LazyLawyerDetails1BreadcrumbEn: LazyComponent<typeof import("../components/lawyer-details-1/BreadcrumbEn.vue")['default']>
export const LazyLawyerDetails1CTAAr: LazyComponent<typeof import("../components/lawyer-details-1/CTAAr.vue")['default']>
export const LazyLawyerDetails1CTAEn: LazyComponent<typeof import("../components/lawyer-details-1/CTAEn.vue")['default']>
export const LazyLawyerDetails1FooterAr: LazyComponent<typeof import("../components/lawyer-details-1/FooterAr.vue")['default']>
export const LazyLawyerDetails1FooterEn: LazyComponent<typeof import("../components/lawyer-details-1/FooterEn.vue")['default']>
export const LazyLawyerDetails1HeroAr: LazyComponent<typeof import("../components/lawyer-details-1/HeroAr.vue")['default']>
export const LazyLawyerDetails1HeroEn: LazyComponent<typeof import("../components/lawyer-details-1/HeroEn.vue")['default']>
export const LazyLawyerDetails1LawyerDetailsAr: LazyComponent<typeof import("../components/lawyer-details-1/LawyerDetailsAr.vue")['default']>
export const LazyLawyerDetails1LawyerDetailsEn: LazyComponent<typeof import("../components/lawyer-details-1/LawyerDetailsEn.vue")['default']>
export const LazyLawyerDetails1LawyerProfileAr: LazyComponent<typeof import("../components/lawyer-details-1/LawyerProfileAr.vue")['default']>
export const LazyLawyerDetails1LawyerProfileEn: LazyComponent<typeof import("../components/lawyer-details-1/LawyerProfileEn.vue")['default']>
export const LazyLawyerDetails1TeamGridAr: LazyComponent<typeof import("../components/lawyer-details-1/TeamGridAr.vue")['default']>
export const LazyLawyerDetails1TeamGridEn: LazyComponent<typeof import("../components/lawyer-details-1/TeamGridEn.vue")['default']>
export const LazyLawyerDetails2BreadcrumbAr: LazyComponent<typeof import("../components/lawyer-details-2/BreadcrumbAr.vue")['default']>
export const LazyLawyerDetails2BreadcrumbEn: LazyComponent<typeof import("../components/lawyer-details-2/BreadcrumbEn.vue")['default']>
export const LazyLawyerDetails2CTAAr: LazyComponent<typeof import("../components/lawyer-details-2/CTAAr.vue")['default']>
export const LazyLawyerDetails2CTAEn: LazyComponent<typeof import("../components/lawyer-details-2/CTAEn.vue")['default']>
export const LazyLawyerDetails2FooterAr: LazyComponent<typeof import("../components/lawyer-details-2/FooterAr.vue")['default']>
export const LazyLawyerDetails2FooterEn: LazyComponent<typeof import("../components/lawyer-details-2/FooterEn.vue")['default']>
export const LazyLawyerDetails2HeroAr: LazyComponent<typeof import("../components/lawyer-details-2/HeroAr.vue")['default']>
export const LazyLawyerDetails2HeroEn: LazyComponent<typeof import("../components/lawyer-details-2/HeroEn.vue")['default']>
export const LazyLawyerDetails2LawyerDetailsAr: LazyComponent<typeof import("../components/lawyer-details-2/LawyerDetailsAr.vue")['default']>
export const LazyLawyerDetails2LawyerDetailsEn: LazyComponent<typeof import("../components/lawyer-details-2/LawyerDetailsEn.vue")['default']>
export const LazyLawyerDetails2LawyerProfileAr: LazyComponent<typeof import("../components/lawyer-details-2/LawyerProfileAr.vue")['default']>
export const LazyLawyerDetails2LawyerProfileEn: LazyComponent<typeof import("../components/lawyer-details-2/LawyerProfileEn.vue")['default']>
export const LazyLawyerDetails2TeamGridAr: LazyComponent<typeof import("../components/lawyer-details-2/TeamGridAr.vue")['default']>
export const LazyLawyerDetails2TeamGridEn: LazyComponent<typeof import("../components/lawyer-details-2/TeamGridEn.vue")['default']>
export const LazyLawyerDetails3BreadcrumbAr: LazyComponent<typeof import("../components/lawyer-details-3/BreadcrumbAr.vue")['default']>
export const LazyLawyerDetails3BreadcrumbEn: LazyComponent<typeof import("../components/lawyer-details-3/BreadcrumbEn.vue")['default']>
export const LazyLawyerDetails3CTAAr: LazyComponent<typeof import("../components/lawyer-details-3/CTAAr.vue")['default']>
export const LazyLawyerDetails3CTAEn: LazyComponent<typeof import("../components/lawyer-details-3/CTAEn.vue")['default']>
export const LazyLawyerDetails3FooterAr: LazyComponent<typeof import("../components/lawyer-details-3/FooterAr.vue")['default']>
export const LazyLawyerDetails3FooterEn: LazyComponent<typeof import("../components/lawyer-details-3/FooterEn.vue")['default']>
export const LazyLawyerDetails3HeroAr: LazyComponent<typeof import("../components/lawyer-details-3/HeroAr.vue")['default']>
export const LazyLawyerDetails3HeroEn: LazyComponent<typeof import("../components/lawyer-details-3/HeroEn.vue")['default']>
export const LazyLawyerDetails3LawyerDetailsAr: LazyComponent<typeof import("../components/lawyer-details-3/LawyerDetailsAr.vue")['default']>
export const LazyLawyerDetails3LawyerDetailsEn: LazyComponent<typeof import("../components/lawyer-details-3/LawyerDetailsEn.vue")['default']>
export const LazyLawyerDetails3LawyerProfileAr: LazyComponent<typeof import("../components/lawyer-details-3/LawyerProfileAr.vue")['default']>
export const LazyLawyerDetails3LawyerProfileEn: LazyComponent<typeof import("../components/lawyer-details-3/LawyerProfileEn.vue")['default']>
export const LazyLawyerDetails3TeamGridAr: LazyComponent<typeof import("../components/lawyer-details-3/TeamGridAr.vue")['default']>
export const LazyLawyerDetails3TeamGridEn: LazyComponent<typeof import("../components/lawyer-details-3/TeamGridEn.vue")['default']>
export const LazyLightEnAccreditations: LazyComponent<typeof import("../components/light-en/Accreditations.vue")['default']>
export const LazyLightEnBlog: LazyComponent<typeof import("../components/light-en/Blog.vue")['default']>
export const LazyLightEnCTA: LazyComponent<typeof import("../components/light-en/CTA.vue")['default']>
export const LazyLightEnFooter: LazyComponent<typeof import("../components/light-en/Footer.vue")['default']>
export const LazyLightEnHeader: LazyComponent<typeof import("../components/light-en/Header.vue")['default']>
export const LazyLightEnHero: LazyComponent<typeof import("../components/light-en/Hero.vue")['default']>
export const LazyLightEnServices: LazyComponent<typeof import("../components/light-en/Services.vue")['default']>
export const LazyLightEnTeam: LazyComponent<typeof import("../components/light-en/Team.vue")['default']>
export const LazyLightEnTestimonials: LazyComponent<typeof import("../components/light-en/Testimonials.vue")['default']>
export const LazyLightEnWhyUs: LazyComponent<typeof import("../components/light-en/WhyUs.vue")['default']>
export const LazyLightAccreditations: LazyComponent<typeof import("../components/light/Accreditations.vue")['default']>
export const LazyLightBlog: LazyComponent<typeof import("../components/light/Blog.vue")['default']>
export const LazyLightCTA: LazyComponent<typeof import("../components/light/CTA.vue")['default']>
export const LazyLightFooter: LazyComponent<typeof import("../components/light/Footer.vue")['default']>
export const LazyLightHeader: LazyComponent<typeof import("../components/light/Header.vue")['default']>
export const LazyLightHero: LazyComponent<typeof import("../components/light/Hero.vue")['default']>
export const LazyLightServices: LazyComponent<typeof import("../components/light/Services.vue")['default']>
export const LazyLightTeam: LazyComponent<typeof import("../components/light/Team.vue")['default']>
export const LazyLightTestimonials: LazyComponent<typeof import("../components/light/Testimonials.vue")['default']>
export const LazyLightWhyUs: LazyComponent<typeof import("../components/light/WhyUs.vue")['default']>
export const LazyServices1BreadcrumbAr: LazyComponent<typeof import("../components/services-1/BreadcrumbAr.vue")['default']>
export const LazyServices1BreadcrumbEn: LazyComponent<typeof import("../components/services-1/BreadcrumbEn.vue")['default']>
export const LazyServices1CTAAr: LazyComponent<typeof import("../components/services-1/CTAAr.vue")['default']>
export const LazyServices1CTAEn: LazyComponent<typeof import("../components/services-1/CTAEn.vue")['default']>
export const LazyServices1HeroAr: LazyComponent<typeof import("../components/services-1/HeroAr.vue")['default']>
export const LazyServices1HeroEn: LazyComponent<typeof import("../components/services-1/HeroEn.vue")['default']>
export const LazyServices1ServicesListAr: LazyComponent<typeof import("../components/services-1/ServicesListAr.vue")['default']>
export const LazyServices1ServicesListEn: LazyComponent<typeof import("../components/services-1/ServicesListEn.vue")['default']>
export const LazyServices2CTAAr: LazyComponent<typeof import("../components/services-2/CTAAr.vue")['default']>
export const LazyServices2CTAEn: LazyComponent<typeof import("../components/services-2/CTAEn.vue")['default']>
export const LazyServices2FooterAr: LazyComponent<typeof import("../components/services-2/FooterAr.vue")['default']>
export const LazyServices2FooterEn: LazyComponent<typeof import("../components/services-2/FooterEn.vue")['default']>
export const LazyServices2ServicesGridAr: LazyComponent<typeof import("../components/services-2/ServicesGridAr.vue")['default']>
export const LazyServices2ServicesGridEn: LazyComponent<typeof import("../components/services-2/ServicesGridEn.vue")['default']>
export const LazyServices3CTAAr: LazyComponent<typeof import("../components/services-3/CTAAr.vue")['default']>
export const LazyServices3CTAEn: LazyComponent<typeof import("../components/services-3/CTAEn.vue")['default']>
export const LazyServices3FooterAr: LazyComponent<typeof import("../components/services-3/FooterAr.vue")['default']>
export const LazyServices3FooterEn: LazyComponent<typeof import("../components/services-3/FooterEn.vue")['default']>
export const LazyServices3ServicesGridAr: LazyComponent<typeof import("../components/services-3/ServicesGridAr.vue")['default']>
export const LazyServices3ServicesGridEn: LazyComponent<typeof import("../components/services-3/ServicesGridEn.vue")['default']>
export const LazyServices4CTAAr: LazyComponent<typeof import("../components/services-4/CTAAr.vue")['default']>
export const LazyServices4CTAEn: LazyComponent<typeof import("../components/services-4/CTAEn.vue")['default']>
export const LazyServices4FooterAr: LazyComponent<typeof import("../components/services-4/FooterAr.vue")['default']>
export const LazyServices4FooterEn: LazyComponent<typeof import("../components/services-4/FooterEn.vue")['default']>
export const LazyServices4ServicesGridAr: LazyComponent<typeof import("../components/services-4/ServicesGridAr.vue")['default']>
export const LazyServices4ServicesGridEn: LazyComponent<typeof import("../components/services-4/ServicesGridEn.vue")['default']>
export const LazyServices5CTAAr: LazyComponent<typeof import("../components/services-5/CTAAr.vue")['default']>
export const LazyServices5CTAEn: LazyComponent<typeof import("../components/services-5/CTAEn.vue")['default']>
export const LazyServices5FooterAr: LazyComponent<typeof import("../components/services-5/FooterAr.vue")['default']>
export const LazyServices5FooterEn: LazyComponent<typeof import("../components/services-5/FooterEn.vue")['default']>
export const LazyServices5ServicesGridAr: LazyComponent<typeof import("../components/services-5/ServicesGridAr.vue")['default']>
export const LazyServices5ServicesGridEn: LazyComponent<typeof import("../components/services-5/ServicesGridEn.vue")['default']>
export const LazySharedLanding4HeaderAr: LazyComponent<typeof import("../components/shared-landing-4/HeaderAr.vue")['default']>
export const LazySharedLanding4HeaderEn: LazyComponent<typeof import("../components/shared-landing-4/HeaderEn.vue")['default']>
export const LazySharedLanding4HeroAr: LazyComponent<typeof import("../components/shared-landing-4/HeroAr.vue")['default']>
export const LazySharedLanding4HeroEn: LazyComponent<typeof import("../components/shared-landing-4/HeroEn.vue")['default']>
export const LazyTeam1CTAAr: LazyComponent<typeof import("../components/team-1/CTAAr.vue")['default']>
export const LazyTeam1CTAEn: LazyComponent<typeof import("../components/team-1/CTAEn.vue")['default']>
export const LazyTeam1FooterAr: LazyComponent<typeof import("../components/team-1/FooterAr.vue")['default']>
export const LazyTeam1FooterEn: LazyComponent<typeof import("../components/team-1/FooterEn.vue")['default']>
export const LazyTeam1HeroAr: LazyComponent<typeof import("../components/team-1/HeroAr.vue")['default']>
export const LazyTeam1HeroEn: LazyComponent<typeof import("../components/team-1/HeroEn.vue")['default']>
export const LazyTeam1TeamGridAr: LazyComponent<typeof import("../components/team-1/TeamGridAr.vue")['default']>
export const LazyTeam1TeamGridEn: LazyComponent<typeof import("../components/team-1/TeamGridEn.vue")['default']>
export const LazyTeam2CTAAr: LazyComponent<typeof import("../components/team-2/CTAAr.vue")['default']>
export const LazyTeam2CTAEn: LazyComponent<typeof import("../components/team-2/CTAEn.vue")['default']>
export const LazyTeam2FooterAr: LazyComponent<typeof import("../components/team-2/FooterAr.vue")['default']>
export const LazyTeam2FooterEn: LazyComponent<typeof import("../components/team-2/FooterEn.vue")['default']>
export const LazyTeam2HeroAr: LazyComponent<typeof import("../components/team-2/HeroAr.vue")['default']>
export const LazyTeam2HeroEn: LazyComponent<typeof import("../components/team-2/HeroEn.vue")['default']>
export const LazyTeam2TeamGridAr: LazyComponent<typeof import("../components/team-2/TeamGridAr.vue")['default']>
export const LazyTeam2TeamGridEn: LazyComponent<typeof import("../components/team-2/TeamGridEn.vue")['default']>
export const LazyTeam3CTAAr: LazyComponent<typeof import("../components/team-3/CTAAr.vue")['default']>
export const LazyTeam3CTAEn: LazyComponent<typeof import("../components/team-3/CTAEn.vue")['default']>
export const LazyTeam3FooterAr: LazyComponent<typeof import("../components/team-3/FooterAr.vue")['default']>
export const LazyTeam3FooterEn: LazyComponent<typeof import("../components/team-3/FooterEn.vue")['default']>
export const LazyTeam3HeaderAr: LazyComponent<typeof import("../components/team-3/HeaderAr.vue")['default']>
export const LazyTeam3HeaderEn: LazyComponent<typeof import("../components/team-3/HeaderEn.vue")['default']>
export const LazyTeam3HeroAr: LazyComponent<typeof import("../components/team-3/HeroAr.vue")['default']>
export const LazyTeam3HeroEn: LazyComponent<typeof import("../components/team-3/HeroEn.vue")['default']>
export const LazyTeam3TeamGridAr: LazyComponent<typeof import("../components/team-3/TeamGridAr.vue")['default']>
export const LazyTeam3TeamGridEn: LazyComponent<typeof import("../components/team-3/TeamGridEn.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
